MODULE M
  TYPE T
    INTEGER :: I
  CONTAINS
    PROCEDURE :: F => T_F
    PROCEDURE :: HOP => T_G
  END TYPE T

CONTAINS
  SUBROUTINE T_F(SELF)
    CLASS(T) :: SELF
    WRITE(*,*) "CALLED T_F"
  END SUBROUTINE T_F
  SUBROUTINE T_G(SELF)
    CLASS(T) :: SELF
    WRITE(*,*) "CALLED T_G"
  END SUBROUTINE T_G
END MODULE
