MODULE M
  TYPE T
    INTEGER :: I
  CONTAINS
    PROCEDURE :: F => T_F
  END TYPE T

  TYPE TT
    REAL :: R
    TYPE(T) :: MON_T
  CONTAINS
    PROCEDURE :: PRINT => TT_PRINT
  END TYPE TT

  TYPE MTT
    TYPE(T) :: MON_T
    TYPE(TT) :: MON_TT
  CONTAINS
    PROCEDURE :: PRINT => MTT_PRINT
  END TYPE MTT

CONTAINS
  SUBROUTINE T_F(SELF)
  CLASS(T) :: SELF
  WRITE(*,*) "CALLED T_F"
END SUBROUTINE T_F
SUBROUTINE TT_PRINT(SELF)
  CLASS(TT) :: SELF
  WRITE(*,*) "CALLED TT_PRINT"
END SUBROUTINE TT_PRINT
SUBROUTINE MTT_PRINT(SELF)
  CLASS(MTT) :: SELF
  WRITE(*,*) "CALLED MTT_PRINT"
END SUBROUTINE MTT_PRINT
END MODULE
